# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS_Coding' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS_Coding
  pod 'Kingfisher', '5.14.0'

  target 'iOS_CodingTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
